### ISSUE TITLE
Create endpoint for copyright takedowns

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-api#294] opened 2019-05-02 16:18 UTC
Currently, responding to takedown requests is a manual and slow process; we should automate it.

Implement a `DELETE /image/{uuid}` call which removes an image from the API database and the search index, and sets the `removed_from_source=True` flag in the upstream catalog database.

The endpoint should accept a username and password to ensure the caller is authorized to perform the deletion.

**Comment by krysal** [comment] 2019-10-12 21:15
I would like to work on this.

**Comment by aldenstpage** [comment] 2019-10-21 18:24
Hi Krysal, go ahead!

**Comment by aldenstpage** [comment] 2019-10-25 17:21
Here's some additional background I gave on this issue on Slack:

In our system, we have three different datastores:

```
Upstream  ----->      API      ----->  Search engine
(postgres)         (postgres)          (Elasticsearch)
```

"Upstream" is a database where we collect the "raw" image metadata from the internet. Before it is loaded into the API/CC Search, we do some cleaning and then copy the whole thing into the downstream database. Then, finally, we index it in Elasticsearch. So to delete a work, we need to do three things:

1. Delete it from the API database
2. Delete it from Elasticsearch
3. Mark the image as deleted from upstream.


Why not delete it from upstream? Our scraping software will end up re-introducing the image into the database if we do that. Instead, we retain the metadata and mark it as deleted. In our system, we do that with a boolean field called "removed_from_source".

I suggest deleting the image from Elasticsearch next (step 2). Step 3 could be solved by making a direct connection to the upstream database from the API and altering the record, but there might be a better way architecturally (right now, the API doesn't talk to upstream at all, which is by design)

**Comment by krysal** [comment] 2019-11-12 13:15
Task completed with points 2 and 3. Waiting for comments.

**Comment by annatuma** [comment] 2019-12-05 21:18
@aldenstpage heads up, I'm moving this to the In Progress column for the upcoming sprint, so you can work with @krysal to close this out during the next sprint.

**Closed** 2020-01-17 16:37 UTC
Labels: enhancement, good first issue, help wanted, in progress
