### ISSUE TITLE
no data result for Museums Victoria filter when it says 170 photos are avail

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-api#280] opened 2019-04-23 18:49 UTC
https://ccsearch.creativecommons.org/search?q=vase&provider=museumsvictoria&li=&lt=&searchBy

![museums victoria bug](https://user-images.githubusercontent.com/6394777/56607608-d21f4600-65bd-11e9-96fe-1dde2c5c090f.png)

**Comment by aldenstpage** [comment] 2019-04-24 17:37
The problem is that the thumbnails for this particular provider don't have a protocol specified, which makes it impossible to validate that the image exists (at least without doubling the amount of requests we send to providers where this edge case applied). I'm going to adjust our ingestion scripts to cleanup the thumbnail field as well. This will be fixed next time we re-ingest the data - it will be a few days.

**Comment by aldenstpage** [comment] 2019-04-30 14:03
The thumbnails weren't the only issue. The images are still filtered because they are a little bit slow to respond to image validation and time out. We have a 200ms timeout before we assume that the images are broken. Because Museums Victoria servers are hosted in Australia, it can take more than a second for a response to come back to our servers in North America.

We can raise the timeout, but it will come at the cost of slower searches (each search will be as fast as its slowest-to-respond image, at least before caching) and higher utilization of our server resources. Since we are experiencing a surge in traffic due to making CC Search the default on cc.org, I'm going to wait a few days before taking action on this, since high traffic + slow responses may cause downtime.

```
alden@cc-laptop:~$ time curl -I https://collections.museumvictoria.com.au/content/media/8/2058-medium.jpg
HTTP/1.1 200 OK
Cache-Control: public, max-age=86400
Content-Length: 182411
Content-Type: image/jpeg
Last-Modified: Sat, 14 May 2016 03:41:13 GMT
ETag: "8d37ba998ac3e14"
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Link,Total-Results,Total-Pages
Date: Tue, 30 Apr 2019 13:52:44 GMT


real	0m1.261s
user	0m0.056s
sys	0m0.000s
```

**Closed** 2019-05-20 17:09 UTC
Labels: bug
