### ISSUE TITLE
Consider self-hosting Elasticsearch on EC2 to reduce AWS costs

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-api#149] opened 2018-11-27 18:59 UTC

**Comment by anoited007** [comment] 2020-02-22 14:22
@aldenstpage Can this be a good GSOC or Outreachy project since it has been left unattended for a while?

**Comment by kgodey** [comment] 2020-02-24 18:55
@anoited007 we do want to work on this, but since it involves access to our infrastructure, I don't think it's suitable for outside contribution.

**Comment by kgodey** [comment] 2020-02-28 20:14
This is a duplicate of https://github.com/creativecommons/ccsearch-infrastructure/issues/120. This belongs in the infrastructure repo anyway, so I'm closing this.

**Closed by kgodey** 2020-02-28 20:14 UTC
Labels: cost optimization
