### ISSUE TITLE
Error in web_1 container

### ISSUE THREAD

**Issue by kintawer** [creativecommons/cccatalog-api#230] opened 2019-03-12 18:52 UTC
Anyone can help me? I'm beginner in docker.
```
web_1               | GET http://es:9200/ [status:N/A request:0.004s]
web_1               | Traceback (most recent call last):
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
web_1               |     (self._dns_host, self.port), self.timeout, **extra_kw)
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
web_1               |     raise err
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
web_1               |     sock.connect(sa)
web_1               |   File "/usr/local/lib/python3.7/site-packages/gevent/_socket3.py", line 335, in connect
web_1               |     raise error(err, strerror(err))
web_1               | ConnectionRefusedError: [Errno 111] Connection refused
web_1               | 
web_1               | During handling of the above exception, another exception occurred:
web_1               | 
web_1               | Traceback (most recent call last):
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
web_1               |     chunked=chunked)
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
web_1               |     conn.request(method, url, **httplib_request_kw)
web_1               |   File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
web_1               |     self._send_request(method, url, body, headers, encode_chunked)
web_1               |   File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
web_1               |     self.endheaders(body, encode_chunked=encode_chunked)
web_1               |   File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
web_1               |     self._send_output(message_body, encode_chunked=encode_chunked)
web_1               |   File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
web_1               |     self.send(msg)
web_1               |   File "/usr/local/lib/python3.7/http/client.py", line 956, in send
web_1               |     self.connect()
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
web_1               |     conn = self._new_conn()
web_1               |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
web_1               |     self, "Failed to establish a new connection: %s" % e)
web_1               | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1ba5a61898>: Failed to establish a new connection: [Errno 111] Connection refused
```

**Comment by dhruvkb** [comment] 2019-03-12 20:01
Can you confirm if your ElasticSearch container started up correctly? This error might indicate that ES did not start up due to insufficient map count. See issue #221 and PR #224 for a fix. That involves adding the line
```
vm.max_map_count=262144
```
to your `/etc/sysctl.conf` file and then rebooting your machine.

**Comment by aldenstpage** [comment] 2019-03-12 20:14
Please [join us on Slack](https://slack-signup.creativecommons.org/) in the #cc-gsoc channel if you are having problems getting started. I'm going to close this issue since it's not a bug.

**Closed by aldenstpage** 2019-03-12 20:14 UTC
Labels: invalid
